version: '3.4'

services:
  app:
    image: kennethreitz/httpbin
    ports:
      - "18080:80"
    environment:
      GUNICORN_CMD_ARGS: "--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
